name: dependencias_comuns
description: Pacote contendo as dependências utilizadas em outros projetos
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.1
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  intl: any
  audioplayers: ^5.2.1
  media_kit: ^1.1.10+1
  media_kit_libs_audio: ^1.0.4
  path_provider: ^2.1.1
  easy_stepper: ^0.8.1
  flutter_localizations:
    sdk: flutter
  pluto_grid: ^7.0.2
  mask_text_input_formatter: ^2.5.0
  barcode_widget: ^2.0.4
  material_symbols_icons: ^4.2711.0
  printing: ^5.11.1
  image: ^4.1.3
  context_menus: ^1.0.2
  device_info_plus: ^9.1.1
  universal_html: ^2.2.4
  touchable: ^1.0.2
  provider: ^6.1.2
  web_socket_channel: ^2.4.0
  xml: ^6.5.0
  font_awesome_flutter: ^10.7.0
  file_picker: ^5.5.0
  flutter_typeahead: ^5.2.0
  clipboard: ^0.1.3
  window_manager: ^0.3.9
  shimmer: ^3.0.0
  pluto_grid_export: ^1.0.6
  cryptography: ^2.7.0
  reactive_forms: ^17.0.1
  reactive_color_picker: ^2.0.1
  dropdown_search: ^5.0.6
  easy_debounce: ^2.0.3
  resizable_widget: ^1.0.5
  screenshot: ^2.5.0
  auto_updater: ^0.2.1
  package_info_plus: ^5.0.1
  uuid: ^4.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  #json_serializable: ^6.7.1

flutter:
  uses-material-design: true