include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_types: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    hash_and_equals: true
    implementation_imports: true
    library_prefixes: true
    no_duplicate_case_values: true
    omit_local_variable_types: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_equal_for_default_values: true
    prefer_final_fields: false
    prefer_final_locals: false
    prefer_final_in_for_each: false
    prefer_is_empty: true
    prefer_mixin: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    slash_for_doc_comments: true
    sort_constructors_first: false
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_overrides: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    valid_regexps: true
    unnecessary_parenthesis: true
    require_trailing_commas: true
    avoid_unnecessary_containers: true
    prefer_contains: true
    prefer_final_parameters: false
    always_use_package_imports: true
    non_constant_identifier_names: ignore